### ISSUE TITLE
Create Visualizations for Galaxies as recommended by the Paper Below

### ISSUE THREAD

**Issue by umesh-timalsina** [KyleAMoore/Redshift-ResNet#6]
In the original paper followed by https://github.com/umesh-timalisna/redshift, they used a technique to visualize RGB images of the galaxies based on the article here: http://www.aspbooks.org/publications/461/263.pdf. We should do a similar representation.

**Comment by KyleAMoore** [comment]
Galaxy image processing and display completed as faithfully as possible to the cited paper. Slight changes to alpha value and brightness cuts were made due to the images being atypical compared to those described in the paper (sparse and zoomed).

Example output images also included with final commit.
